### PR TITLE
Remove unnecessary attributes from feature.xml files

### PR DESCRIPTION
**Pull request by HannesWell**
Apply the result of https://github.com/eclipse-pde/eclipse.pde/issues/730.

### CODE REVIEW

**Comment by HannesWell** [comment]
> @HannesWell Your local system timezone or time is off. You create commits in the future.

Locally all looks fine:

grafik

And I didn't change my settings recently and the time-switch in Germany last weekend went smooth I think.

So if North-America has a switch this weekend as Ed said, I assume that's an issue at the GH server side.

**Comment by Bananeweizen** [comment]
Looking at the non-linear posting thread remembers me of this one. :)
5345829660_0518ff8c1b

**Comment by HannesWell** [comment]
> Looking at the non-linear posting thread reminds me of this one. :)

😄
There really seem to be some issues. I was wondering where my comment when after pushing the Comment button and noticed after a minute that it simply went up before the comment it responses too... 😵

**Comment by Bananeweizen** [comment]
@HannesWell Your local system timezone or time is off. You create commits in the future.
grafik

**Pull request merged**
